---
# tasks file for ansible-role-moosefs
# Configure your MooseFS cluster.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure the main master configuration
  template:
    src: mfsmaster.cfg.j2
    dest: /etc/mfs/mfsmaster.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_master' in group_names"
  notify: reload mfsmaster

- name: Configure the main topology configuration
  template:
    src: mfstopology.cfg.j2
    dest: /etc/mfs/mfstopology.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_master' in group_names"
  notify: reload mfsmaster

- name: Configure the main exports
  template:
    src: mfsexports.cfg.j2
    dest: /etc/mfs/mfsexports.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_master' in group_names"
  no_log: true
  notify: reload mfsmaster

- name: Configure the main metalogger configuration
  template:
    src: mfsmetalogger.cfg.j2
    dest: /etc/mfs/mfsmetalogger.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_metalogger' in group_names"

- name: Configure the main chunkserver configuration
  template:
    src: mfschunkserver.cfg.j2
    dest: /etc/mfs/mfschunkserver.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_chunkserver' in group_names"
  notify: reload mfschunkserver

- name: Build a list of bricks
  find:
    paths: /mnt/bricks
    patterns: "*"
    file_type: directory
  when: "'moosefs_chunkserver' in group_names"
  register: brick_list

- name: Configure the chunkserver brick list
  template:
    src: mfshdd.cfg.j2
    dest: /etc/mfs/mfshdd.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_chunkserver' in group_names"

- name: Configure the MooseFS client
  template:
    src: mfsmount.cfg.j2
    dest: /etc/mfs/mfsmount.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_client' in group_names"

- name: Mark MooseFS as configured
  set_fact:
    moosefs_configured: true
