---
# tasks file for ansible-role-moosefs
# Configure your MooseFS cluster.

# Conditionally load in variables for chosen version of MooseFS
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ moosefs_version }}.yml'
    - ../vars/versions/default.yml
  include_vars: '{{ item }}'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure the main master configuration
  template:
    src: mfsmaster.cfg.j2
    dest: /etc/mfs/mfsmaster.cfg
    owner: root
    group: root
    mode: '0644'
  when: "'moosefs_master' in group_names"
