---
# tasks file for ansible-role-moosefs
# main tasks file, which performs pretty much everything needed for installation and configuration of MooseFS
# Conditionally load in variables for chosen version of MooseFS
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ moosefs_version }}.yml'
    - ../vars/versions/default.yml
  include_vars: '{{ item }}'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: build-from-source.yml
  when: moosefs_install_method == "build"
