---
# tasks file for ansible-role-moosefs
# main tasks file, which performs pretty much everything needed for installation and configuration of MooseFS
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

### Install MooseFS ###
# Install MooseFS from official packages
- include_tasks: install-official.yml
  when: moosefs_install_method == "official"

# Build and install MooseFS from source for hosts using build method (current default)
- include_tasks: install-source.yml
  when: moosefs_install_method == "build" and not moosefs_pro

# Install MooseFS from distro packages
- include_tasks: install-from-package.yml
  when: moosefs_install_method == "package" and not moosefs_pro

### Check installation ###
# Check if MooseFS is now installed
# TODO - consider making this a loop

- name: Check if MooseFS is installed (master)
  stat: path=/usr/sbin/mfsmaster
  register: moosefs_install_check
  when: "'moosefs_master' in group_names"

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true

- name: Check if MooseFS is installed (cgiserv)
  stat: path=/usr/sbin/mfscgiserv
  register: moosefs_install_check

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true

- name: Check if MooseFS is installed (metalogger)
  stat: path=/usr/sbin/mfsmetalogger
  register: moosefs_install_check

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true

- name: Check if MooseFS is installed (chunkserver)
  stat: path=/usr/sbin/mfschunkserver
  register: moosefs_install_check

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true

- name: Check if MooseFS is installed (client)
  stat: path=/usr/bin/mfsmount
  register: moosefs_install_check

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true

### Post-installation ###
# Once MooseFS is installed, create configuration files and prepare things
- include_tasks: check-bricks.yml
  when: moosefs_installed

- include_tasks: configure-moosefs.yml
  when: moosefs_installed

# Now that MooseFS is configured, start and enable services
- include_tasks: start-services.yml
  when: moosefs_configured

# Automount MooseFS if automount is enabled
- include_tasks: mount-moosefs.yml
  when: moosefs_automount
