---
# tasks file for ansible-role-moosefs
# main tasks file, which performs pretty much everything needed for installation of MooseFS
# Conditionally load in variables for chosen version of MooseFS
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ moosefs_version }}.yml'
    - ../vars/versions/default.yml
  include_vars: '{{ item }}'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Build and install MooseFS from source for hosts using build method (current default)
- include_tasks: build-from-source.yml
  when: moosefs_install_method == "build"

# Set up MooseFS repos for hosts using package method
- include_tasks: install-from-package.yml
  when: moosefs_install_method == "package"

# Check if MooseFS is now installed
- name: Check if MooseFS is installed
  stat: path=/usr/sbin/mfsmaster
  register: moosefs_install_check
  when: moosefs_install_method == "build"

- name: MooseFS install check - store the result
  set_fact:
    moosefs_installed: true
  when: moosefs_install_method == "build"
