---
# tasks file for ansible-role-moosefs
# Mount MooseFS
- name: Define our mountpoint
  set_fact:
    moosefs_mountpoint: /mnt/mfs

- name: Check if MooseFS is working
  file:
    path: /mnt/mfs/.moosefs-ansible-test
    state: touch
    owner: root
    group: root
    mode: 0755
