---
# tasks file for ansible-role-moosefs
# Mount MooseFS

- name: Create our mountpoint
  file:
    path: "{{ moosefs_mount_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create an entry in /etc/fstab
  lineinfile:
    path: "/etc/fstab"
    line: "mfsmount {{ moosefs_mount_path }} fuse defaults,mfsdelayedinit,nofail 0 0"
    state: present

- name: Mount MooseFS
  command:
    cmd: mfsmount
  when: ansible_mounts | selectattr('mount', 'equalto', moosefs_mount_path) | list | length == 0

- name: Check if MooseFS is working
  file:
    path: "{{ moosefs_mount_path }}/.moosefs-ansible-test"
    state: touch
    owner: root
    group: root
    mode: 0755
