---
# tasks file for ansible-role-moosefs
# Mount MooseFS

- name: Create our mountpoint
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ moosefs_mount }}"
  no_log: true

- name: Create an entry in /etc/fstab
  lineinfile:
    path: "/etc/fstab"
    line: "mfsmount {{ item.path }} fuse mfssubfolder={{ item.mfssubfolder }},{{ item.options }},mfspassword={{ item.mfspassword }} 0 0"
    state: present
  loop: "{{ moosefs_mount }}"
  no_log: true

# Automatically mount MooseFS

- name: Check that each MooseFS mountpoint is mounted
  mount:
    name: "{{ item.path }}"
    src: "mfsmount"
    fstype: fuse
    opts: "mfssubfolder={{ item.mfssubfolder }},{{ item.options }},mfspassword={{ item.mfspassword }}"
    state: mounted
  loop: "{{ moosefs_mount }}"
  no_log: true

# Only works for default system mount anyways
# - name: Mount MooseFS
#   command:
#     cmd: mfsmount
#   when: 
#     - ansible_mounts | selectattr('mount', 'equalto', moosefs_mount_path) | list | length == 0

# Disabled for now, we'll find a cleaner way to do it later.
# - name: Check if MooseFS is working
#   file:
#     path: "{{ moosefs_mount_path }}/.moosefs-ansible-test"
#     state: touch
#     owner: root
#     group: root
#     mode: 0755