---
# tasks file for ansible-role-moosefs

# Start and enable MooseFS master
- name: Start and enable MooseFS master
  service:
    name: moosefs-master
    state: started
    enabled: true
  when: "'moosefs_master' in group_names"

# Start and enable MooseFS metalogger
- name: Start and enable MooseFS metalogger
  service:
    name: moosefs-metalogger
    state: started
    enabled: true
  when: "'moosefs_metalogger' in group_names"

# Start and enable MooseFS chunkserver
- name: Start and enable MooseFS chunkserver
  service:
    name: moosefs-chunkserver
    state: started
    enabled: true
  when: "'moosefs_chunkserver' in group_names"

# Start and enable MooseFS client
- name: Start and enable MooseFS client
  service:
    name: moosefs-client
    state: started
    enabled: true
  when: "'moosefs_client' in group_names"
