---
# tasks file for ansible-role-moosefs

# Start and enable MooseFS master
- name: Start and enable MooseFS master
  service:
    name: moosefs-master
    state: started
    enabled: true
  when: "'moosefs_master' in group_names and not moosefs_pro"

- name: Start and enable MooseFS master (PRO)
  service:
    name: moosefs-pro-master
    state: started
    enabled: true
  when: "'moosefs_master' in group_names and moosefs_pro"

# Start and enable MooseFS cgiserv
- name: Start and enable MooseFS cgiserv
  service:
    name: moosefs-cgiserv
    state: started
    enabled: true
  when: "'moosefs_master' in group_names and not moosefs_pro"

- name: Start and enable MooseFS cgiserv (PRO)
  service:
    name: moosefs-pro-cgiserv
    state: started
    enabled: true
  when: "'moosefs_master' in group_names and moosefs_pro"

# Start and enable MooseFS metalogger
- name: Start and enable MooseFS metalogger
  service:
    name: moosefs-metalogger
    state: started
    enabled: true
  when: "'moosefs_metalogger' in group_names and not moosefs_pro"

- name: Start and enable MooseFS metalogger (PRO)
  service:
    name: moosefs-pro-metalogger
    state: started
    enabled: true
  when: "'moosefs_metalogger' in group_names and moosefs_pro"

# Start and enable MooseFS chunkserver
- name: Start and enable MooseFS chunkserver
  service:
    name: moosefs-chunkserver
    state: started
    enabled: true
  when: "'moosefs_chunkserver' in group_names and not moosefs_pro"

- name: Start and enable MooseFS chunkserver (PRO)
  service:
    name: moosefs-pro-chunkserver
    state: started
    enabled: true
  when: "'moosefs_chunkserver' in group_names and moosefs_pro"
